var labels = {
    lblTitle: ['LDN Ecuador', 'NDT Ecuador'],
    lblLCPieChartChange: ['Land Cover change', 'Cambio de Uso del Suelo'],
    lblLCperLPD: ['LC per LPD', 'Uso x Productividad'],
    lblLPDperLC: ['LPD per LC', 'Productividad x Uso'],
    lblSOCperLC: ['SOC mean per LC', 'Carbono Org. Suelo x Uso'],
    lblSOCperLPD: ['SOC mean per LPD', 'Carbono Org. Suelo x Productividad'],
    lblSOCperLCLPD: ['SOC mean per LC/LPD', 'Carbono Org. Suelo x Uso/Productividad'],
    lblSOCStats: ['SOC stats', 'Estadísticas de Carbono Org. Suelo'],
    lblProjectAreas: ['Project units', 'Unidades de proyecto'],
    lblSelectedProjectAreas: ['Selected area', 'Área seleccionada'],
    lblOnlyProjectAreas: ['Prefilter only countries with project', ''],
    lblLayers: ['Layers', 'Capas'],
    lblSoilOrganicCarbon: ['Soil Organic Carbon (SOC)', 'Carbono Orgánico del Suelo (COS)'],
    lblSocVeryLow: ['Very low','Muy Bajo'],
    lblSocLow: ['Low','Bajo' ],
    lblSocModerateLow: ['Moderate Low','Moderado bajo'],
    lblSocModerateHigh: ['Moderate high','Moderado alto'],
    lblSocHigh: ['High','Alto'],
    lblSocVeryHigh: ['Very high', 'Muy alto'],      
    lblLandCover: ['Land Cover', 'Cobertura del Suelo'],
    lblLandProductivityDynamics: ['Land Productivity Dynamics', 'Dinámica de la Productividad Vegetal'],
    lblSocMean: ['SOC Mean', 'COS Promedio'],
    lblSocMax: ['SOC Max', 'COS Máximo'],
    lblSocMin: ['SOC Min', 'COS Mínimo'],
    lblMonthly: ['Monthly', 'Mensual'],
    lblAnnual: ['Annual', 'Anual'],
    lblYear: ['Year', 'Año'],
    lblTreeCovered: ['Native forest', 'Bosque nativo'],
    lblGrassland: ['Grassland', 'Pastizal/Arbustal'],
    lblCropland: ['Cropland', 'Cultivos'],
    lblWetland: ['Wetland', 'Humedal'],
    lblArtificial: ['Artificial', 'Artificial'],
    lblOtherLand: ['Other land', 'Otras tierras'],
    lblWaterbody: ['Water body', 'Agua'],
    lblForests: ['Planted forests', 'Plantaciones forestales'],
    lblParamo: ['Paramo', 'Páramo'],
    lblDeclining: ['Declining', 'Disminución'],
    lblEarlySignDecline: ['Early sign of decline', 'Deterioro Incipiente'],
    lblStableButStressed: ['Stable but stressed', 'Estable pero Estresado'],
    lblStable: ['Stable', 'Estable'],
    lblIncreasing: ['Increasing', 'Aumento'],
    lblExpl1: ['This platform aims to support decision-making to achieve Land Degradation Neutrality in Ecuador by identifying priority areas for the implementation of sustainable management practices and the integration of qualitative and quantitative indicators relevant to the monitoring and evaluation of land degradation.',
        'Esta plataforma tiene como objetivo dar apoyo a la toma de decisiones para lograr la Neutralidad de la Degradación de las Tierra en Ecuador mediante la identificación de zonas prioritarias para la implementación de prácticas sustentables de manejo y la integración de indicadores cualitativos y cuantitativos relevantes para el monitoreo y evaluación de la degradación de las tierras.'],
    lblExpl2: ['Choose a province or canton from the list below or click on the map to get statistics.',
        'Seleccione una provincia o cantón de la lista o haga click en el mapa para obtener estadísticas.'],
    lblAssetClick: ['Select which layer you want to click on: ', 'Seleccione en qué capa desea hacer click: '],
    lblExpl3: ['',
        ''],
    lblSelectDistrict: ['Select district', 'Seleccione distrito'],
    lblCharts: ['Charts', 'Gráficos'],
    lblAreaName: ['Name', 'Nombre'],
    lblAppDeveloped: ['For questions and feedback please contact:  ',
        ''],
    lblLoading: ['Loading...', 'Cargando...'],
    lblSOCTonnesHa: ['SOC tonnes/ha', 'COS toneladas/ha'],
    lblGeneratingCharts: ['Generating chart ', 'Generando gráfico '],
    lblCalculating: ['Calculating...', 'Calculando...'],
    lblNoAreaSelected: ['No area selected', 'No hay área seleccionada'],
    lblAbsolute: ['Absolute', 'Absoluto'],
    lblRelative: ['Relative', 'Relativo'],
    lblMonthlyNDVI: ['Monthly NDVI MODIS(MOD13Q1)', 'NDVI Mensual MODIS(MOD13Q1)'],
    lblAnnualNDVI: ['Annual Mean NDVI MODIS (MOD13Q1)', 'NDVI Anual MODIS(MOD13Q1)'],
    lblSelectedAOI: ['Selected area of interest', 'Área de interés seleccionada'],
    lblCalendarYear: ['Calendar year', 'Año calendario'],
    lblSocSum: ['SOC Stock', 'COS Stock'],
    lblCombinedCategoriesArea: ['Combined categories area ', 'Superficie de la combinación'],
    lblDownload: ['Download combined layer as tif', 'Descargar la capa combinada como tif'],
    lblLCTransitionAnalysis: ['Land Cover transition analysis', 'Transiciones en Uso del Suelo'],
    lblFromLC: ['From Land Cover', 'Desde Uso'],
    lblCurrentLC: ['To Land Cover', 'Hasta Uso'],
    lblGains: ['Gains', 'Ganancias'],
    lblLosses: ['Losses', 'Pérdidas'],
    lblSelectLCYear: ['Initial year', 'Año inicial'],
    lblClickMoreInfo: ['Click here for more information about this project.', 'Presione aquí para ver más información sobre este proyecto.'],
    lblStep1: ['Select LC (2019-Copernicus): ', 'Seleccionar categorías de CS: '],
    lblStep2: ['Select LPD: ', 'Seleccionar categorías de DPV: '],
    lblStepDisplay: ['Click "Calculate" to preview layer, "Reset" for new categories selection.',
        'Presione "Calcular" para visualizar la capa, "Reestablecer" para realizar una nueva combinación.'],
    lblDisplay: ['Calculate', 'Calclular'],
    lblReset: ['Reset', 'Reestablecer'],
    lblDecliningProductivity: ['Declining productivity', 'Productividad decreciente'],
    lblIncreasingProductivity: ['Increasing productivity', 'Productividad creciente'],
    lblArea: ['Area', 'Área'],
    lblNoChange: ['No change', 'Sin cambio'],
    lblHotspots: ['Multi-Criteria Analysis', 'Análisis de Multicriterio'],
    lblFrontLayerOpacity: ['Front layer opacity:', 'Opacidad: '],
    lblNoData: ['No data', 'Sin datos'],
    lblTopography: ['Topography', 'Topografía'],
    lblTableLC: ['Areas with Land Cover changes', 'Áreas con cambios en el Uso'],
    lblTableLCLPD: ['Productivity dynamics for each land cover', 'DPV para cada Uso'],
    lblLC: ['LC', 'CS'],
    lblLPD: ['LPD', 'DPV'],
    lblDifference: ['Difference', 'Diferencia'],
    lblStep3: ['Select Mountain categories: ', 'Seleccionar las categorías de montaña: '],
    lblSelectLanguage: ['Please select language', 'Por favor seleccionar idioma'],
    lblDrawingTools: ['Drawing tool', 'Herramienta de dibujo'],
    lblDownloadCsv: ['Download as csv', 'Descargar como csv'],
    lblDownloadJson: ['Download drawn features in .csv', 'Descargar elementos dibujados en .csv'],
    lblDownloadKml: ['Download drawn features in .kml', 'Descargar elementos dibujados en .kml'],
    lblDownloadFileName: ['Drawn-features', 'Elementos-dibujados'],
    lblExplDrawing: ['Use the drawing tool in the upper left corner of the map panel if you want to draw points/polygons and download them to your local machine. Please notice that as features are drawn download links (json and kml) are updated. To add a layer fill the layer name input below and then click "+" button.'
        , 'Use la herramienta de dibujo en la esquina superior izquierda del panel del mapa si desea dibujar puntos/polígonos y descargarlos en su ordenador. Tenga en cuenta que a medida que dibuja elementos, los links (json y kml) se actualizan. Para agregar una capa introduza el nombre en la caja de texto de abajo y presione el botón "+".'],
    lblUpdating: ['Updating', 'Actualizando'],
    lblWithMountains: ['Mountain area', 'Área con montaña'],
    lblNoMountains: ['Non mountain area', 'Área sin montaña'],
    lblMountain1: ['≥ 4500m', '≥ 4500m'],
    lblMountain2: ['3500-4500m', '3500-4500m'],
    lblMountain3: ['2500-3500m', '2500-3500m'],
    lblMountain4: ['1500-2500m slope ≥2°', '1500-2500m slope ≥2°'],
    lblMountain5: ['1000-1500m slope ≥5°', '1000-1500m slope ≥5°'],
    lblMountain6: ['300-1000m LER >300m', '300-1000m LER >300m'],
    lblMountain7: ['Inner plateau <25km2', 'Inner plateau <25km2'],
    lblMountains: ['Mountains', 'Montañas'],
    lblTerrain: ['Topography', 'Topografía'],
    lblSelectContainer: ['Select Ecuador', 'Seleccionar Ecuador'],
    lblSelectContainer2: ['', ''],
    lblLandscape: ['Landscape area', ''],
    lblBigImage: ['It is not posible to download generated image.', 'No es posible descargar la imagen generada.'],
    lblGeneralCharts: ['General Charts', 'Gráficos generales'],
    lblHotspotsCharts: ['Combined LC/LPD/SOC Charts', 'Gráficos con CS/DPV/COS combinados'],
    lblTransitionsCharts: ['Landuse Transitions Charts', 'Gráficos de transición de Uso'],
    lblProtectedAreas: ['Protected Areas', 'Áreas protegidas'],
    lblNonProtectedAreas: ['Non Protected Areas', 'Áreas No protegidas'],
    lblProtectedArea: ['Protected Area', 'Área protegida'],
    lblKeyBiodiversityAreas: ['Key Biodiversity Areas', 'Áreas clave de biodiversidad'],
    lblPrecipitationTrend: ['Precipitation Trend 2000-2020', 'Tendencia en las precipitaciones 2000-2020'],
    lblNegTrend: ['- Trend', 'Tendencia -'],
    lblPosTrend: ['+ Trend', 'Tendencia +'],
    lblKeyBiodiversityArea: ['Key Biodiversity Area', 'Área clave de biodiversidad'],
    lblMountainCoverage: ['Mountain Coverage', 'Cobertura de montaña'],
    lblInfo: ['Info', 'Info'],
    lblClose: ['Close', 'Cerrar'],
    lblCloseWarning: ['(You can reopen this panel later by clicking the "Info" button)',
        '(Puede reabrir este panel luego presionando el botón "Info")'],
    lblLayerName: ['Layer Name', 'Nombre de la capa'],
    lblLoadingLevel1: ['Loading provinces...', 'Cargando provincias...'],
    lblLoadingLevel2: ['Loading cantons...', 'Cargando cantones...'],
    lblSelectLevel1: ['Select province', 'Seleccione provincia'],
    lblSelectLevel2: ['Select canton', 'Seleccione cantón'],
    lblSelectLevel1First: ['Select province first', 'Seleccione primero una pcia.'],
    lblLevel1: ['Provinces', 'Provincias'],
    lblLevel2: ['Cantons', 'Cantones'],
    lblQM: ['QM Mapping Units', 'Unidades de Mapeo QM'],
    lblLUS: ['Land Use Systems', 'Sistemas de Uso de Suelo'],
    lblSelectLUS: ['Select LUS', 'Seleccione Sistema de Uso de Suelo'],
    lblQMMappingUnit: ['QM Mapping Unit', 'Unidad de mapeo QM'],
    lblHihInfo: ['Hand In Hand Info', 'Info Hand In Hand'],
    lblLevelLUS: ['Land Use System', 'Sistema de Uso de la Tierra'],
    lblForestGain: ['Forest gain', 'Ganancia de bosques'],
    lblForestLoss: ['Forest loss', 'Pérdida de bosques'],
    lblFireIndex: ['Fire index (Recurrence 2001-2020)', 'Índice de fuego (recurrencia 2001-2020)'],
    lblForestGainsLosses: ['Forest Gain&Loss (Copernicus 2015-2019)', 'Pérdidas y ganancias de bosque'],
    lblGeneratingDownloadLink: ['Generating download link...', 'Generando link de descarga...'],
    lblDeforestation: ['Deforestation (Ha)', 'Deforestación (Ha)'],
    lblNetLCChanges: ['Net LC Changes (ha)', 'Cambios netos de CS (ha)'],
    lblLCSource: ['LC source', 'Fuente de CS'],
    lblSocMap: ['Soil Organic Carbon', 'Carbono Orgánico del Suelo'],
    lblNone: ['None', 'Ninguna'],
    lblSelectGeometry: ['Please select a geometry first using the hand icon.', 'Por favor seleccione una geometría primero utilizando el ícono de la mano.'],
    lblCheckout: ['Please check out the right panel.', 'Por favor verifique resultados en el panel de la derecha.'],
    lblProcessing: ['Processing selected drawn-area for statistics, this might take a while...',
        'Procesando el área dibujada para obtener estadísticas, el proceso puede demorar...'],
    lblUnexpectedError: ['Unexpected error occurred while processing geometry.', 'Ha ocurrido un error inesperado procesando la geometría.'],
    lblGeometryNotContained: ['Geometry has to be contained in country area.', 'La geometría debe estar contenida en el área del país.'],
    lblSmallerArea: ['Please select area smaller than ', 'Por favor seleccion un área menor a '],
    lblSelectedAreaHa: ['Selected area: ', 'Área seleccionada: '],
    lblSelectArea: ['Please select an area.', 'Seleccione un área por favor.'],
    lblErrorCalculating: ['An error occurred while calculating area. Please try again or select a smaller area.', 'Ocurrió un error al calcular el área. Por favor inténtelo de nuevo o seleccione un área de menor tamaño.'],
    lblSelectAndCalculate: ['Select drawn-area & calculate  stats', 'Seleccionar área dibujada y calcular estadísticas'],
    lblZonalStats: ['Zonal stats', 'Estadísticas del área'],
    lblProcessingArea: ['Processing area, please wait...', 'Procesando el área, por favor espere...'],
    lblDegExtension: ['Degradation extension', 'Extensión de degradación'],
    lblDegDirCauses: ['Direct causes', 'Causas directas'],
    lblDegType: ['Degradation type', 'Tipo de degradación'],
    lblDegImpact: ['Impact on ES', 'Impactos en SE'],
    lblLow: ['Low', 'Bajo'],
    lblMedium: ['Medium', 'Medio'],
    lblHigh: ['High', 'Alto'],
    lblRuralPoverty: ['HiH Rural Poverty', 'HiH Pobreza Rural'],
    lblTechnicalEfficiency: ['HiH Technical Efficiency', 'HiH Eficiencia Técnica'],
    lblAgriculturalPotential: ['HiH Agriculural Potential', 'HiH Potencial Agrícola'],
    lblQMExtent: ['WOCAT QM Degradation Extent (%)', 'WOCAT QM Extensión de la Degradacion (%)'],
    lblQMExtentperc: ['Degradation in %', 'Degradación en %'],
    lblQMRecommendations: ['WOCAT QM Recommendations', 'WOCAT QM Recomendaciones'],
    lblQMRecommendation: ['Recommendation', 'Recomendación'],
    lblQMDegradationDegree: ['Degradation degree', 'Grado de degradación'],
    lblSelectLayer: ['Please first select which layer you want to click on', 'Por favor primero seleccione qué capa desea consultar'],
    lblNoFeature: ['There is no feature at clicked point', 'No hay ningún área de interés en el punto seleccionad'],
    lblMcSimple: ['Simple', 'Simple'],
    lblMcAdvanced: ['Advanced', 'Avanzado'],
    lblNonVegetatedArea: ['Non vegetated area', 'Área sin vegetación'],
    lblVegetatedArea: ['Vegetated area', 'Área con vegetación'],
    lblDisclaimer: [
        'The boundaries and names shown and the designations used on this map do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal status of any country, territory, city or area or of its authorities, or concerning the delimitation of its frontiers and boundaries',
        'The boundaries and names shown and the designations used on this map do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal status of any country, territory, city or area or of its authorities, or concerning the delimitation of its frontiers and boundaries'
    ],
    lblElevation: ['Elevation', 'Elevación'],
    lblKba: ['KBA', 'KBA'],
    lblNonKba: ['Non KBA', 'No KBA'],
    lblCustomLayer: [
        '1- What will you map? Enter the name and click "+" button. Layer will be added to the map',
        '1- ¿Qué mapearás? Ingresa un nombre y haz click en el botón "+". Una capa con el nombre ingresado se agregará al mapa.'
    ],
    lblDrawFeatures: [
        '2- Select the drawing tool (point or polygon) and draw on the map by clicking',
        '2- Selecciona la herramienta de dibujo (punto o polígono) y dibuja en el mapa haciendo click'
    ],
    lblGetStatistics: [
        '3- Select a polygon in the map (using the hand icon) and click the button below to obtain statistics for the area.',
        '3- Selecciona un polígono en el mapa (utilizando el ícono de la mano) y haz click en el botón de abajo para obtener estadísticas para el área.'
    ],
    lblDownloadLinks: [
        '4- Download your polygons and points (links appear and are updated while drawing)',
        '4- Descarga los polígonos y puntos (los links aparecen abajo y son actualizados mientras se dibuja)'
    ],
    lblLinks: ['Links', 'Links'],
    lblBasins: ['Basins', 'Cuencas'],
    lblSubbasins: ['Sub-basins', 'Subcuencas'],
    lblStepAgriculturalPotential: ['Select Agricultural Potential', 'Seleccione Potencial Agrícola'],
    lblStepRuralPoverty: ['Select Rural Poverty Level', 'Seleccione Nivel de Pobreza Rural'],
    lblStepTechnicalEfficiency: ['Select Technical Efficiency', 'Seleccione Eficiencia Técnica'],
    lblPrevention: ['Prevention', 'Prevención'],
    lblMitigation: ['Mitigation', 'Mitigación'],
    lblRehabilitation: ['Rehabilitation', 'Rehabilitación'],
    lblAdaptation: ['Adaptation', 'Adaptación'],
    lblQMDegree: ['WOCAT QM Degree of Degradation', 'WOCAT QM Grado de la Degradación'],
    lblLight: ['Light', 'Leve'],
    lblModerate: ['Moderate', 'Moderado'],
    lblStrong: ['Strong', 'Fuerte'],
    lblExtreme: ['Extreme', 'Extremo'],
    lblQMDirectCauses: ['WOCAT QM Direct Causes', 'WOCAT QM Causas Directas'],
    lblIndustrial: ['Mining and industrial activities', 'Actividades industriales y minería'],
    lblHydrologicalCycle: ['Alteration of hydrologycal cycle', 'Alteraciones del ciclo hidrológico'],
    lblNaturalCauses: ['Natural causes', 'Causas Naturales'],
    lblVegetationRemoval: ['Deforestation and vegetation removal', 'Deforestación y remoción de la vegetación'],
    lblUrbanDevelopment: ['Urban development', 'Desarrollo urbanístico e infraestructura'],
    lblContaminatingDischarges: ['Contaminating Discharges', 'Descargas Contaminantes'],
    lblCropManagement: ['Crop and rangeland management', 'Manejo de los cultivos y pasturas'],
    lblSoilManagement: ['Soil management', 'Manejo del suelo'],
    lblOverExploitation: ['Over-exploitation of vegetation', 'Sobreexplotación de la vegetación'],
    lblOvergrazing: ['Overgrazing', 'Sobrepastoreo'],
    lblApproach: ['Approach', 'Approach'],
    lblTechnology: ['Technology', 'Technology'],
    lblUNCCDPrais: ['UNCCD Prais', 'UNCCD Prais'],
    lblSLM: ['WOCAT SLM best practices', 'WOCAT MST Buenas Prácticas'],
    lblLink: ['WOCAT database link ', 'Link a base de datos WOCAT'],
    lblNoSLM: ['No SLM point selected', 'Ningún punto MST seleccionado'],
    lblQMImpactEcosystemServices: ['WOCAT QM Impact on ecosystem services', 'WOCAT QM Impacto en los servicios ecosistémicos'],
    lblBiodiversityServices: ['Biodiversity Services', 'Servicios biodiversidad'],
    lblSoilServices: ['Soil Services', 'Servicios edáficos'],
    lblWaterServices: ['Water Service', 'Servicios hídricos'],
    lblProtectionServices: ['Protection Services', 'Servicios prevención riesgos naturales'],
    lblProductiveServices: ['Productive Services', 'Servicios productivos'],
    lblSocioCulturalServices: ['Socio-cultural and human well-bein Services', 'Servicios socio-culturales/bienestar humano'],
    lblQMDegradationTypes: ['WOCAT QM Degradation types', 'WOCAT QM Tipos de degradación'],
    lblBioDeg: ['Biological degradation', 'Degradacion biológica'],
    lblWaterDeg: ['Water degradation', 'Degradación del agua'],
    lblPhysycalDet: ['Physical soil deterioration', 'Deterioro físico del suelo'],
    lblChemicalDet: ['Chemical soil deterioration ', 'Deterioro químico del suelo'],
    lblEolicErosion: ['Soil erosion by wind', 'Erosión eólica'],
    lblWaterErosion: ['Soil erosion by water', 'Erosión hídrica'],
    lblBioGeoSector: ['Biogeographic sectors', 'Sectores biogeográficos'],
    lblBioGeoSector1: ['Aguarico-Putumayo- Caquetá', 'Aguarico-Putumayo- Caquetá'],
    lblBioGeoSector2: ['Napo-Curaray', 'Napo-Curaray'],
    lblBioGeoSector3: ['Tigre-Pastaza', 'Tigre-Pastaza'],
    lblBioGeoSector4: ['Abanico del Pastaza', 'Abanico del Pastaza'],
    lblBioGeoSector5: ['Cordillera Amazónica', 'Cordillera Amazónica'],
    lblBioGeoSector6: ['Norte de la Cordillera Oriental de los Andes', 'Norte de la Cordillera Oriental de los Andes'],
    lblBioGeoSector7: ['Sur de la Cordillera Oriental del os Andes', 'Sur de la Cordillera Oriental del os Andes'],
    lblBioGeoSector8: ['Páramo', 'Páramo'],
    lblBioGeoSector9: ['Valles', 'Valles'],
    lblBioGeoSector10: ['Cordillera Occidental de los Andes', 'Cordillera Occidental de los Andes'],
    lblBioGeoSector11: ['Catamayo-Alamor', 'Catamayo-Alamor'],
    lblBioGeoSector12: ['Chocó Ecuatorial', 'Chocó Ecuatorial'],
    lblBioGeoSector13: ['Cordillera Costera del Chocó', 'Cordillera Costera del Chocó'],
    lblBioGeoSector14: ['Cordillera Costera del Pacífico Ecuatorial', 'Cordillera Costera del Pacífico Ecuatorial'],
    lblBioGeoSector15: ['Jama-Zapotillo', 'Jama-Zapotillo'],

};

var languages = ['English', 'Spanish'];
exports.languages = languages;

var getLocLabels = function (lan) {
    var loc = {};
    var index = languages.indexOf(lan);
    Object.keys(labels).forEach(function (key) {
        loc[key] = labels[key][index];
    });
    return loc;
}
exports.getLocLabels = getLocLabels;